#!/bin/sh

echo "/* This file is autogenerated by $0 - do not edit */"
echo

while read atom
do
    case $atom in
      "_"*) echo xcb_atom_t ATOM$atom\; ;;
      *)    echo xcb_atom_t ATOM_$atom\; ;;
    esac
done < $1

echo
echo 'static atom_item_t ATOM_LIST[] ='
echo '{'

while read atom
do
    case $atom in
      "_"*) echo '    { "'$atom'", sizeof("'$atom'") - 1, &'ATOM$atom' },' ;;
      *) echo '    { "'$atom'", sizeof("'$atom'") - 1, &'ATOM_$atom' },' ;;
    esac
done < $1

echo '};'

# vim: filetype=sh:expandtab:shiftwidth=4:tabstop=8:softtabstop=4:textwidth=80
